<?php

return [
    'store_name'    => env('STORE_NAME', 'THRIFT SECONDSTORE'),
    'store_tagline' => env('STORE_TAGLINE', 'Hoodie thrift pilihan dengan kondisi terbaik.'),
    'store_about'   => env('STORE_ABOUT', 'Kami adalah toko thrift yang fokus pada hoodie dan fashion streetwear pilihan dengan kualitas terbaik.'),
    'store_since'   => env('STORE_SINCE', '2024'),
    'store_location'=> env('STORE_LOCATION', 'Indonesia'),
    'whatsapp_number' => env('WHATSAPP_NUMBER', '6281234567890'),
    'catalog_season' => env('CATALOG_SEASON', 'FALL WINTER 2026'),
    'catalog_title' => env('CATALOG_TITLE', 'THRIFT LOOKBOOK'),

    // Kategori produk — dipakai di filter katalog & form admin
    'product_types' => [
        'hoodie'    => ['label' => 'Hoodie',       'emoji' => '🧥', 'pairing' => ['pants', 'shorts']],
        'jacket'    => ['label' => 'Jaket',         'emoji' => '🧥', 'pairing' => ['pants', 'shorts']],
        'tshirt'    => ['label' => 'Kaos',          'emoji' => '👕', 'pairing' => ['pants', 'shorts']],
        'shirt'     => ['label' => 'Kemeja',        'emoji' => '👔', 'pairing' => ['pants']],
        'pants'     => ['label' => 'Celana Panjang','emoji' => '👖', 'pairing' => ['hoodie', 'jacket', 'tshirt', 'shirt']],
        'shorts'    => ['label' => 'Celana Pendek', 'emoji' => '🩳', 'pairing' => ['hoodie', 'tshirt']],
        'shoes'     => ['label' => 'Sepatu',        'emoji' => '👟', 'pairing' => []],
        'bag'       => ['label' => 'Tas',           'emoji' => '👜', 'pairing' => []],
        'hat'       => ['label' => 'Topi',          'emoji' => '🧢', 'pairing' => []],
        'belt'      => ['label' => 'Ikat Pinggang', 'emoji' => '🪢', 'pairing' => []],
        'scarf'     => ['label' => 'Syal / Scarf',  'emoji' => '🧣', 'pairing' => []],
        'accessory' => ['label' => 'Aksesori',      'emoji' => '💍', 'pairing' => []],
        'other'     => ['label' => 'Lainnya',       'emoji' => '📦', 'pairing' => []],
    ],
    'social_links' => [
        'instagram' => env('SOCIAL_INSTAGRAM', 'https://www.instagram.com/thrift.secondstore/'),
        'tiktok' => env('SOCIAL_TIKTOK', 'https://www.tiktok.com/@secondstore.id'),
        'tokopedia' => env('SOCIAL_TOKOPEDIA', 'https://www.tokopedia.com/'),
        'shopee' => env('SOCIAL_SHOPEE', 'https://shopee.co.id/'),
    ],
    'cover_image' => env('CATALOG_COVER_IMAGE', 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80'),

    // Brand storytelling — Slow Fashion & nilai brand
    'brand_story' => [
        'tagline'       => env('BRAND_TAGLINE', 'Fashion yang bermakna, bukan sekadar mengikuti tren.'),
        'mission'       => env('BRAND_MISSION', 'Kami percaya setiap pakaian punya cerita. Thrift bukan soal murah — tapi tentang memilih dengan sadar, mengurangi limbah, dan menemukan gaya yang autentik.'),
        'slow_fashion'  => env('BRAND_SLOW_FASHION', 'Setiap produk di platform kami adalah pilihan kurasi dari mitra terpercaya. Kami mendukung slow fashion: beli yang kamu butuhkan, pakai lebih lama, dan jual kembali saat sudah tidak cocok.'),
        'values'        => [
            ['icon' => '🌱', 'title' => 'Eco-Conscious', 'desc' => 'Kurangi limbah fashion dengan membeli pre-loved berkualitas.'],
            ['icon' => '✋', 'title' => 'Handpicked', 'desc' => 'Setiap item dikurasi mitra dengan standar kondisi tinggi.'],
            ['icon' => '🏠', 'title' => 'Lokal & Mitra', 'desc' => 'Mendukung toko thrift lokal di seluruh Indonesia.'],
            ['icon' => '♻️', 'title' => 'Circular Fashion', 'desc' => 'Beli, pakai, jual kembali — siklus fashion berkelanjutan.'],
        ],
        'timeline'      => [
            ['year' => env('STORE_SINCE', '2024'), 'title' => 'Dimulai dari Passion', 'desc' => 'Berawal dari kecintaan pada streetwear & thrift, kami membangun katalog digital pertama.'],
            ['year' => '2025', 'title' => 'Platform Multi-Mitra', 'desc' => 'Membuka pintu bagi toko thrift lokal bergabung dan berkembang bersama.'],
            ['year' => '2026', 'title' => 'Lookbook Interaktif', 'desc' => 'Meluncurkan pengalaman visual dengan hotspot produk dan editorial fashion.'],
        ],
    ],

    // Template kolom size chart
    'size_chart_columns' => [
        'size'     => 'Ukuran',
        'chest'    => 'Dada (cm)',
        'length'   => 'Panjang (cm)',
        'shoulder' => 'Bahu (cm)',
        'sleeve'   => 'Lengan (cm)',
        'waist'    => 'Pinggang (cm)',
        'hip'      => 'Pinggul (cm)',
    ],
    'size_chart_defaults' => [
        ['size' => 'S',  'chest' => '50', 'length' => '65', 'shoulder' => '44', 'sleeve' => '58'],
        ['size' => 'M',  'chest' => '54', 'length' => '68', 'shoulder' => '46', 'sleeve' => '60'],
        ['size' => 'L',  'chest' => '58', 'length' => '71', 'shoulder' => '48', 'sleeve' => '62'],
        ['size' => 'XL', 'chest' => '62', 'length' => '74', 'shoulder' => '50', 'sleeve' => '64'],
    ],

    'products' => [
        [
            'slug' => 'hoodie-vintage-navy',
            'name' => 'Dickies Essential Hoodie Navy',
            'brand' => 'Dickies',
            'price' => 235000,
            'size' => 'L',
            'condition' => '9.2/10',
            'description' => 'Hoodie Dickies warna navy dengan cutting regular, bahan fleece tebal, cocok untuk daily.',
            'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
            'is_active' => true,
        ],
        [
            'slug' => 'hoodie-oversize-cream',
            'name' => 'WHO.A.U Oversize Hoodie Cream',
            'brand' => 'WHO.A.U',
            'price' => 215000,
            'size' => 'XL',
            'condition' => '9/10',
            'description' => 'Model oversize warna cream dari WHO.A.U, fit santai untuk style street casual.',
            'image' => 'https://images.unsplash.com/photo-1618354691551-44de113f0164?auto=format&fit=crop&w=900&q=80',
            'is_active' => true,
        ],
        [
            'slug' => 'hoodie-black-classic',
            'name' => 'Carhartt Pullover Hoodie Black',
            'brand' => 'Carhartt',
            'price' => 265000,
            'size' => 'M',
            'condition' => '9/10',
            'description' => 'Hoodie hitam klasik dengan logo kecil depan, bahan nyaman dan masih sangat layak.',
            'image' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80',
            'is_active' => true,
        ],
        [
            'slug' => 'hoodie-grey-essential',
            'name' => 'Stussy Logo Hoodie Grey',
            'brand' => 'Stussy',
            'price' => 285000,
            'size' => 'L',
            'condition' => '8.8/10',
            'description' => 'Hoodie abu netral dengan logo chest print, cocok untuk layering dan daily wear.',
            'image' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80',
            'is_active' => true,
        ],
        [
            'slug' => 'nike-club-fleece-hoodie',
            'name' => 'Nike Club Fleece Hoodie',
            'brand' => 'Nike',
            'price' => 245000,
            'size' => 'L',
            'condition' => '9/10',
            'description' => 'Nike hoodie seri fleece dengan warna netral, nyaman dipakai harian.',
            'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',
            'is_active' => true,
        ],
        [
            'slug' => 'adidas-heritage-hoodie',
            'name' => 'Adidas Heritage Hoodie',
            'brand' => 'Adidas',
            'price' => 225000,
            'size' => 'M',
            'condition' => '8.7/10',
            'description' => 'Hoodie Adidas gaya basic sporty, warna clean dan mudah dipadukan.',
            'image' => 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
            'is_active' => true,
        ],
    ],
];
